### ISSUE TITLE
nix env for building and running hermes

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#107]
add a nixos "thing" to run hermes as a service on a nixos system

@nc6 could you help with this ?

**Comment by nc6** [comment]
I can probably help. Is there an existing systemd unit?

**Comment by vincenthz** [comment]
no, but writing one would be helpful too for sure. Also we should probably tweak our options to be more daemon friendly @NicolasDP. I'm not sure having hermes having subcommand is a good idea. all options on the command line might be good enough ?

**Comment by nc6** [comment]
This is being annoyingly tricky! The nixpkgs build infrastructure for rust seems a bit fragile.
