### ISSUE TITLE
replace termion by termcolor

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#138]
termion doesn't work on windows, so need to replace by termcolor for coloring and possibly an line piece for the noecho part. termcolor is used by cargo, so is a safe bet.

**Comment by NicolasDP** [comment]
one of the problem is the input password, it'd be nice to have something to handle that safely for us without needing to write too much code.

I guess we could look at: [console](https://crates.io/crates/console) and [dialoguer](https://crates.io/crates/dialoguer)
