### ISSUE TITLE
Is this going to be a monolith repository?

### ISSUE THREAD

**Issue by sjmackenzie** [input-output-hk/rust-cardano#156]
Will you guys be publishing the "sub" crates to crates.io so that others may create "thin" wrapper clients around them?

In other words, is this going to be a monolith repository?

Reference Sputnikvm and how it publishes subcrates to crates.io  https://github.com/ETCDEVTeam/sputnikvm/blob/master/Cargo.toml and how a wrapper program etcclient makes use of them https://github.com/sorpaas/etclient/blob/master/Cargo.toml

I'd suggest this strategy would be optimal for more diversified client implementations, where you can guarantee the necessary crates that compose clients are correct. Also the use of `cardano = { path = "../cardano" }` is forbidden on crates.io.

**Comment by vincenthz** [comment]
short term plans is to publish `cbor-events`, `cryptoxide`, and `cardano` as their own crates soon; this repository will still build more or less the same way for now though.

**Comment by sjmackenzie** [comment]
Great! I'd like to integrate this code into Fractalide to create a new client, so publishing as many crates as possible would be great (at least for us!).

**Comment by vincenthz** [comment]
the more high level crates (e.g. storage, network, etc..) are not for consumption just yet anyway, it's really about developping some capabilities and toolbox which are driven with one use case, but once we got more users and use cases, hopefully we can define sensible abstractions and develop things as needed and together.

**Comment by sjmackenzie** [comment]
I suppose an anti-pattern would be `parity`. That's a huge monolithic application woven together using relative paths from hell. `rust-cardano` would be practically useless to us if that were the case. Integrating your code is still several months off. Look forward to it.
