### ISSUE TITLE
C exports for fully functional binding library

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#184]
Adding APIs and interfaces for:

* [x] wallet creation
* [x] account creation
* [x] address creation
* [x] address validation
* [ ] address structure
* [ ] utxo representation
* [ ] signing transaction
* [ ] transaction querying
* [ ] transaction preparation interface
* [ ] fee calculation

**Comment by thangchq-ibl** [comment]
Hi @vincenthz ,
Appreciate your update. We are trying to support our Cardano from our mobile wallet (built on React Native for both iOS and Android); so going to use **cardano-c** repository. Any idea when will the rest of the functionality be ready?

Regards,

**Comment by Captainkoko** [comment]
@vincenthz @NicolasDP how is it going? Any update for the progress of C binding library?

**Comment by vincenthz** [comment]
@Captainkoko we've been busy and focus with another aspect of the project, and hopefully we'll get to the binding probably this month. lots of tasks should be simple enough, that anyone requiring certain bindings could add it themselves. Anyone is more than welcome to start chipping away at the bindings
