### ISSUE TITLE
cardano-cli uses a fork of dialoguer

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/rust-cardano#215]
This is needed since #214 as we needed to allow empty passwords. We can start reusing mainstream dialoguer as soon as mitsuhiko/dialoguer#6 is merged and released.

**Comment by NicolasDP** [comment]
I am moving the issue to the new dedicated repo input-output-hk/cardano-cli#1

**Comment by sjmackenzie** [comment]
I suspect this news means I no longer need to be using git submodules and/or `carnix` won't choke on the code! :-)

**Comment by NicolasDP** [comment]
only if you need to compile [`input-output-hk/cardano-cli`](https://github.com/input-output-hk/cardano-cli) with `carnix`

**Comment by sjmackenzie** [comment]
Thankfully we'll not be needing https://github.com/input-output-hk/cardano-cli (anything more than reference code).

Just a few observations you guys might like to know on our pain points thus far:
* No git modules in `Cargo.toml` as `carnix` chokes on them. 
* As this repository is not published on crates.io we're doing nasty hacking by making this repository a git submodule of our project as we don't want to directly commit the code into our repository. Hydra our CI system chokes on submodules. So we have to hack on hydra to build git submodules. The best solution is to publish to crates.io. 
* Ideally a crates strategy revolves around useful work units: this example is probably the best https://github.com/ETCDEVTeam/etcommon-rs which is included in a repository here: https://github.com/sorpaas/etclient/blob/master/Cargo.toml

**Comment by sjmackenzie** [comment]
In our project you could imagine one `"node"` would only include something like this: https://github.com/sorpaas/etclient/blob/master/Cargo.toml#L12 and not the whole crate so to say. So ideally a nice separation of concerns at crate level would be ideal.

**Comment by sjmackenzie** [comment]
The main point I want to convey is the "Rolling Release Section" at the bottom: https://github.com/ETCDEVTeam/etcommon-rs#rolling-release

**Comment by sjmackenzie** [comment]
I'll create a separate issue for these points.
