### ISSUE TITLE
How to build on mobile for both iOS and Android?

### ISSUE THREAD

**Issue by thangchq-ibl** [input-output-hk/rust-cardano#226]
Hi everyone,
Currently we are developing a mobile wallet using React Native for iOS and Android. And we really love to support Cardano in our wallet. 
Please let us know which is the better way:
1. Run **[cardano wasm binding for JavaScript](https://github.com/input-output-hk/js-cardano-wasm)** on React Native. (We tried and failed to build, any suggestion?)
2. Compile **rust cardano** to native library (iOS and Android); then write bridges of them for React Native.

Your help is much appreciated,
Best regards.

**Comment by NicolasDP** [comment]
Hi @thangchq-ibl ,

1. there is a build script in the cardano wasm binding repo did you use it? Could you [open an issue in this repo so we can work there to help you build JS bindings](https://github.com/input-output-hk/js-cardano-wasm/issues/new), adding logs and other information to help us reproduce the issue would be very helpful too.
2. it is possible to compile to **iOS** or **Android**. we have started a _c binding_ library in [`cardano-c`](https://github.com/input-output-hk/rust-cardano/tree/master/cardano-c). However the APIs is **not stabilized** and is not thoroughly tested.

**Comment by thangchq-ibl** [comment]
Thank you very much @NicolasDP for your reply. We are are trying the 2nd approach at the moment following [this guideline](https://github.com/input-output-hk/rust-cardano/blob/master/cardano-c/README.md). Will ask for help again if needed.

**Comment by Captainkoko** [comment]
Hi @NicolasDP ,
Thanks for your diligent support. We were able to compile for native iOS and Android. But problem is there are many core functions [missing at the moment](https://github.com/input-output-hk/rust-cardano/issues/184)....
Any suggestion we can overcome the dire situation?

Best regards,
Jackie Pham

**Comment by thangchq-ibl** [comment]
Hi @NicolasDP,
I tried to build *.so for Android from cardano-c by config Cargo.toml ([config reference](https://doc.rust-lang.org/reference/linkage.html)) by using **cdylib**:
```
[package]
name = "cardano-c"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>", "Vincent Hanquez <vincent.hanquez@iohk.io>"]

[lib]
crate-type = ["cdylib" ]

[dependencies]
cardano = { path = "../cardano" }
```
But I meet error: 
```
./build.sh armv7-linux-androideabi
## compile library for target: `armv7-linux-androideabi'

 * toolchain's target `armv7-linux-androideabi' already installed
 * compiling with debug symbols
warning: unused import: `cardano::config`
 --> cardano-c/src/wallet.rs:5:5
  |
5 | use cardano::config;
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

warning: unused import: `c_char`
 --> cardano-c/src/bip39.rs:1:27
  |
1 | use std::os::raw::{c_int, c_char};
  |                           ^^^^^^

warning: unused imports: `ffi`, `ptr`
 --> cardano-c/src/bip39.rs:2:11
  |
2 | use std::{ffi, slice, ptr};
  |           ^^^         ^^^

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack"
```
Can you have any suggestion? Or can I build cardano-c for .so file?

Many Thanks.

**Comment by NicolasDP** [comment]
@Captainkoko feel free to pop in the #184 ticket, we welcome any contribution/help.
