### ISSUE TITLE
Will you be adding the functions to create a transaction?

### ISSUE THREAD

**Issue by prographo** [input-output-hk/rust-cardano#233]
Will you be adding the functions to create a transaction?

**Comment by NicolasDP** [comment]
It is already possible to create transactions.

https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/wallet/scheme.rs#L45-L59

```rust
    fn new_transaction<'a, I>( &self
                             , protocol_magic: ProtocolMagic
                             , selection_policy: fee::SelectionPolicy
                             , inputs: I
                             , outputs: Vec<TxOut>
                             , output_policy: &OutputPolicy
                             )
            -> fee::Result<(tx::TxAux, fee::Fee)>
        where I : 'a + Iterator<Item = &'a Input<Self::Addressing>> + ExactSizeIterator
            , Self::Addressing: 'a;

```

**Comment by prographo** [comment]
Sorry I thought I was leaving this under the cardano-c subdirectory... That function is in "rust", I don't really know much about rust. Other languages can't call rust functions afaik, but everything calls C. Is it possible to do conversion for new_transaction function to C as has already been done for wallet functions?

**Comment by NicolasDP** [comment]
No worries.

We are finalizing some work on `cardano-cli`. We might be working on the C library next week. As you can see in the link above, we already have the rust main implementation. It is only a question of implementing the C binding now. This is not as easy as it sounds as we wish to make this API rights to meet the needs of all our partners.

You can look at #226 for help regarding building this library to iOS and android (as I understand you will be working on mobile client). And you can look at #184 to follow progress on the C binding library.

Feel free to join us on [Gitter too](https://gitter.im/input-output-hk/Cardano-Rust).

**Comment by NicolasDP** [comment]
I will be closing this ticket as duplicate, as it is super seeded by #184

**Comment by prographo** [comment]
Thanks
