### ISSUE TITLE
module.alloc is not a function  exception

### ISSUE THREAD

**Issue by llcds** [input-output-hk/rust-cardano#24]
module.alloc is not a function

**Comment by llcds** [comment]
installed from npm

**Comment by i-xiaov** [comment]
@llcds  Same issue.  The `RustModule` is initialized asynchronously, make sure it has been prepared before use.
`loadRustModule().then((module) => Object.assign(RustModule, module));`

**Comment by NicolasDP** [comment]
seems the solution from @i-xiaov is working.
