### ISSUE TITLE
Problem: carnix chokes on git attributes in Cargo.toml

### ISSUE THREAD

**Issue by sjmackenzie** [input-output-hk/rust-cardano#241]
We have a nix only setup which allows us to build reusable + reproducible systems. We wish to reduce our CONOP factor to just typing the name and you're done. So we have to use nix.

Solution within these constraints: please [don't use](https://github.com/input-output-hk/rust-cardano/blob/master/cardano-cli/Cargo.toml#L10) git modules in Cargo.tomls in this repository.

**Comment by NicolasDP** [comment]
I think this will be solved via #240

**Comment by sjmackenzie** [comment]
(Understood, @NicolasDP thanks :-), putting this here for posterity sake. )

**Comment by NicolasDP** [comment]
fixed in #240
