### ISSUE TITLE
`change_value` is calculated wrong

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/rust-cardano#253]
Hello! 

This line of code: https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/input_selection.rs#L124

Calculates `change_value` as `(output_value - input_value - estimated_fee)`. This is wrong, since if my transaction contains 5 coins of inputs, 2 coins of outputs, and fee of 0.17 - then change will be calculated as `(2 - 5 - 0.17) = -3.17`.

It should be `(input_value - output_value - estimated_fee)`, so then if will be calculated as `(5 - 2 - 0.17) = 2.83` which is the change.

Currently change does not work, and it's confirmed in this thread: https://forum.cardano.org/t/rust-code-cardano-cli-change-address-fees-not-working-as-expected/15897

**Comment by NicolasDP** [comment]
Hello, thanks for reporting issues to us.

the execution of the algorithm would then fail as `fee` cannot be of negative value. As you can see the complete line of code is:

```rust
if let Ok(change_value) = output_value - input_value - estimated_fee.to_coin()
```

We are pattern matching the return value of the [`Sub`](https://doc.rust-lang.org/std/ops/trait.Sub.html) operator. The implementation of `Sub` for `Coin` returns a `Result<Coin, Error>`.  This is why there is the pattern match `if let Ok(b) = a`. If the subtraction is negative it will return an error which in in the algorithm is considered as _not enough input_.

The issue in the thread you reported is linked to a problem in the `cardano-cli` itself. Issue which I think will be addressed by doing input-output-hk/cardano-cli#14

**Comment by NicolasDP** [comment]
Reopening because this issue actually highlight another problem. We will need to change it in a way that it is easier to review.

**Comment by vantuz-subhuman** [comment]
Thank you very much for clarifications, @NicolasDP!

**Comment by NicolasDP** [comment]
Thanks. I forgot to link the issue. The issue has been addressed in #278

**Comment by vincenthz** [comment]
@datnv-ibl as @NicolasDP mentions, we think we fixed this issue already and we're happy to hear feedback; specially if that doesn't fix it ! But we're happy with some positive feedback too to raise the confidence in the fix.

**Comment by datnv-ibl** [comment]
Thank you, we still using the old version v0.1.2 so we're planning to upgrade to new version as soon as we can.

Thank you for all your hard work.

**Comment by vincenthz** [comment]
@datnv-ibl you're still using the 0.1.2 github "release" from march ? it's only there because we needed to make a release to npm, but it's massively out of date and not really there as a flagship.

**Comment by vincenthz** [comment]
@datnv-ibl ok that's great ! I got really scare while reading "0.1.2" :)

let us know if you need any sort of help for upgrading (also we have a gitter channel for live conversation).
