### ISSUE TITLE
Duplication?

### ISSUE THREAD

**Issue by prographo** [input-output-hk/rust-cardano#269]
Hi, there seems to be duplication in the cardano/ code, there is an HDWallet.rs file and also a wallet/ dir containing similar code. Is there a different purpose? Which should one use?

**Comment by prographo** [comment]
Thx I will look. cargo doc --open gives an error about cbor:

```
$ cargo doc --open 
error: failed to read `/project-cardano-wallet/rust-cardano/cbor_event/Cargo.toml`
Caused by:
  No such file or directory (os error 2)

$ pwd
/project-cardano-wallet/rust-cardano/cardano
```

**Comment by prographo** [comment]
"So you don't need to save the entropy, you can save the cached_key " -- that's downstream from password entry, so they can spend, right? If only the entropy is stored, they still need to enter the password to spend.

**Comment by NicolasDP** [comment]
I'm sorry to read this. On the last commit of this repository, I don't have this problem. Maybe we could close this conversation and seek help on the [gitter chat page](https://gitter.im/input-output-hk/Cardano-Rust) : there are some rust cardano enthusiasts that may help too.

**Comment by prographo** [comment]
Sure thing, thx for your help.
