### ISSUE TITLE
Some questions for getting start with rust-cardano 

### ISSUE THREAD

**Issue by gutenye** [input-output-hk/rust-cardano#308]
1. Where can I find the API documentation?
2. Looks like Cardano uses Ed25519 from rust crypto module. And there's [a wasm binding for JavaScript](https://github.com/input-output-hk/js-cardano-wasm). But can I use any other ed25519 Node.js implementation? If so is there any disadvantages. Or is there some modification to Ed25519, so I can only use [bip32-ed25519](https://github.com/ilap/BIP32-Ed25519/commit/d7e38858c37547689627d1f09ee7a2249806381a) library.
3. How to get it working with bip32?

I need something like
```
1. privateKey is derived from bip32 HD wallet master key.
2. const publicKey = Wallet.getPublicKeyFromPriavteKey(privateKey)
3. const address = Wallet.getAddressFromPublicKey(publicKey)
```

But from the [API](https://github.com/input-output-hk/js-cardano-wasm/blob/master/js/Wallet.js#L17), it only provides `Wallet.fromSeed` method.

**Comment by NicolasDP** [comment]
1. the API documentation is not available online, but you can generate it easily with  `cargo doc --no-deps --open -p cardano` at the root of the repository.

**Comment by vincenthz** [comment]
@gutenye we use a specific implementation of ed25519 only available in https://crates.io/crates/cryptoxide (which is our maintained fork of rust-crypto).

You can use other ed25519's implementation for signing and verification, that operate on the extended secret key, but those implementation are rare (IIRC only sodium provide such capabilities).

I haven't clearly looked, but `fromSeed` is what you're looking for here. bip32 is provided in rust-cardano too, but this is just a way to convert a set of specific words (with a given dictionary), to a seed.

**Comment by gutenye** [comment]
@NicolasDP,	@vincenthz Thanks for the response. I'm going to explore more with it.
