### ISSUE TITLE
Surprising operator overloads for Coin

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/rust-cardano#313]
The impls of `std::ops` arithmetic operator traits for `Coin` have a `Result` type as the output. This somewhat defeats the purpose of operator overloading by encumbering the notation with mandatory result checking, and violates an [API guideline][c-overload] on operator overloading acting predictably.

A more conventional solution for checked math would be methods on `Coin`, similar to the `checked_*` [methods][checked] found on built-in integer types.

[c-overload]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#operator-overloads-are-unsurprising-c-overload
[checked]: https://doc.rust-lang.org/std/primitive.u64.html#method.checked_add

**Comment by vincenthz** [comment]
it's not unpredictable to add a result here, just like the checked api provide you with an option. My take is that, the guideline really talk about using operator to do something not even related to their operation (for example concating with `+`).

Now whether we come up with a better way, we could look into it eventually

**Comment by mzabaluev** [comment]
The user is supposed to be able to do e.g. `a + b + c`.

As a compromise, it may be possible to hide the possible failure in an intermediate result type like `CoinExpression` and have that interoperate with `Coin` operands. Then, the only explicit check to perform would be at the final assignment to a `Coin` value.

Custom method-based APIs can be anything because the method use is self-evident and can be looked up in documentation if necessary. Not so for overloaded operators.

**Comment by mzabaluev** [comment]
Case in point: instead of [code like this](https://github.com/input-output-hk/cardano-cli/blob/d97cf0d9eb9d6bf9d19a3d31ea6f99a3eb1feca3/src/wallet/state/state.rs#L59):

```rust
        let total = iter
            .fold(Ok(Coin::zero()), |acc, v| {
                acc.and_then(|acc| acc + v)
            })?;
```

It should be possible to write like this:

```rust
        let total = iter
            .fold(Coin::zero_acc(), |acc, v| acc + v)
            .try_into()?;
```

Only the final assignment of `CoinExpression` to a valid `Coin` would need an explicit conversion method.
