### ISSUE TITLE
storage-units: minor race conditions in utils::lock

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/rust-cardano#321]
The `Lock` struct in module `utils::lock` of storage-units, while serving its basic purpose, has race conditions that might make error reporting spurious:

* `acquire` has a gap between failing to create the file and opening the presumably existing file (besides, no checking on the error code is done to see if it's really `AlreadyExists`) to read the PID. If the acquirer removes the file in between, an I/O error will be reported instead of the `AlreadyLocked` error.
* Similarly, there is a gap between creating the file and writing the PID into it, when another process can fail to acquire the lock and then fail to read a valid PID from the existing file.

**Comment by amias-iohk** [comment]
i have noticed this while trying to write tests for the lock in https://github.com/input-output-hk/rust-cardano/issues/372
