### ISSUE TITLE
Deref considered harmful

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/rust-cardano#329]
The crates of this project liberally declare `Deref` impls to facilitate coercion between various types. This is [problematic][c-deref] for API maintainability, as it makes the method set available for a type harder to reason about, and makes the result type of operator `*` non-evident from the code. `Deref` should be reserved for smart pointers, and tightly coupled types like owned and borrowed variants for the same data. For "subclass" type relationships and easy conversions to a more basic underlying type, it's preferable to use `AsRef` and explicit ad-hoc reference conversion methods.

[c-deref]: https://rust-lang-nursery.github.io/api-guidelines/predictability.html#c-deref

**Comment by vincenthz** [comment]
I agree, I had a conversation about this topic a while ago with @NicolasDP, and we settled that it was breaking down abstractions to do this. So we should not use this kind of things in the future (apart from exceptions), and eventually remove the one we already have when we clean things up.

it's way more useful for limiting types usage, to set up only the apis you want with strong types, even if they look like other api, than using `Deref`

**Comment by mzabaluev** [comment]
The `Deref` impls for hash types slicing them down to a `[u8; HASH_SIZE]` are particularly problematic, as this can occur without any visible hint in a deref coercion.
