### ISSUE TITLE
`InputSelectionAlgorithm.compute` sometimes returns wrong estimated fee

### ISSUE THREAD

**Issue by vsubhuman** [input-output-hk/rust-cardano#349]
## The problem

This matching case: https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/input_selection/mod.rs#L177

It always assumes that if there are any change outputs added - then `loss` is always `None`. Which is not always true.

This algorithm - https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/txbuild.rs#L174

It rightfully reduces a potential change value until it fits the (inputs - fee). So if (inputs - outputs - fee) gives us a potential change value, but then adding this change value increases fee - then we will reduce the actual change value until it fits the lower fee. But in this case there's a non-zero loss. Which is ignored in the result.

As the result of this - function returns valid tx, but the estimate fee is wrong and does not actually match (inputs - outputs).

## Possible solution

If we agree that "estimated fee" should always match the actual fee encode in the tx - then it might be calculated by either returning correct loss in this matching case (https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/input_selection/mod.rs#L177), **OR** just by calculating factual fee by literally calculating (inputs - outputs), instead of these two lines - https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/input_selection/mod.rs#L184-L185

If we consider that "estimated fee" for some reason should show exactly the **estimated** fee that was estimated, but not the one that is used in the tx itself - then I would argue that there should be an additional field in the result, like `actual_fee`, calculated by literal (inputs - outputs) formula.

**Comment by vantuz-subhuman** [comment]
Kudos to @ppershing for detecting this problem.
