### ISSUE TITLE
Control which output is "paying" the fee

### ISSUE THREAD

**Issue by vsubhuman** [input-output-hk/rust-cardano#353]
## Introduction

When we call Rust wallet to create a [new transaction](https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/wallet/scheme.rs#L72) - we provide it with a list of available inputs and a list of desired outputs. When a simple client uses it - it usually specifies a single output where user wants to send some coins.

Rust performs the coin-selection algorithm and selects some subset `{IN}` of all provided inputs (if enough provided), and value-sum of this subset constitutes the `TOTAL_INPUT` of the transaction.

If `TOTAL_INPUT` exceeds the value-sum of all specified outputs - **additional implicit output** is automatically added to send the extra coins to. This output called the "change output".

But each transaction also has a cost, called "fee", which is **by default** implicitly always subtracted from the change output (because sender "pays" the fee).

So a transaction might be **simplistically** abstractly represented as consisting of:
1. Subset `{IN}` of all provided available inputs, with a positive value `IN.v` associated with each input, where `TOTAL_INPUT = sum(IN.v)`
2. Set of outputs `{OUT}` with a positive value `OUT.v` associated with each output, where `TOTAL_OUTPUT = sum(OUT.v)`
3. Additional output `OUT(CHANGE)`, with associated value `CHANGE`, where `CHANGE = TOTAL_INPUT - TOTAL_OUTPUT`
4. Implicit transaction cost `FEE`, calculated from the transaction size and subtracted from the `CHANGE` value, and if `CHANGE` turns to 0 - `OUT(CHANGE)` is removed too.

## Abstract

We would want to change step 4 to be able to subtract value `FEE` from **any** of the specified outputs. Example:

1. We provide list of available input values, like: `[1, 10, 5, 15, 8]`
2. We provide list of outputs: `[{A: 12, fee: true}]` (where `A` is a receiver address, and `fee` is a parameter indicating that we want to subtract fee from this output). `TOTAL_OUTPUT` = 12
3. Rust selects inputs: `[1, 10, 5]`. `TOTAL_INPUT` = 16
4. Rust calculates `CHANGE = 16 - 12 = 4`, and adds new output: `[{A: 12}, {B: 4}]` (where `B` is a change address from the sender's wallet). `TOTAL_OUTPUT` is now 16.
5. Rust calculates `FEE = 0.1` (just for sake of example)
6. Rust sees that we have marked the output as `fee: true`, so it recalculates values as: [{A: 11.9}, {B: 4}]

This scenario is equal to user manually creating an output of value `DESIRED_SPEND - FEE`, but the problem is that `FEE` is unknown, until the transaction is already constructed and coin selection is performed.

Thus we would like to be able to delegate that math to the Rust, providing better and easier UX. Having a functionality like this will allow clients to implement features like: "fee included" (when sending amount X to someone, and requiring that no more than X actually leaves the wallet), and "send all" (when sending whole own balance to some address, so output might be easily specified as `{A: BALANCE, fee: true}`).

## Technical 

Current logic of transaction construction might be found in here: https://github.com/input-output-hk/rust-cardano/blob/master/cardano/src/input_selection/mod.rs#L124

We can implement the feature by changing the transaction construction a bit toward how I have described it in the example. Something like:

1. Add all provided outputs to the transaction builder
2. Take new inputs (`self.select_input`) until `TOTAL_INPUT >= TOTAL_OUTPUT`. Add all inputs to tx builder.
3. If `(CHANGE = TOTAL_INPUT - TOTAL_OUTPUT) > 0` - create new output with CHANGE as value
3. Estimate FEE from builder
4. If some output is marked as `{fee: true}` - **precision-subtract** FEE from the value of this output (if not enough - throw error)
5. Else if no output is marked:
    1. Until `FEE <= CHANGE` - take new inputs (if none - throw error)
    2. Recalculate CHANGE and FEE
    3. When `FEE <= CHANGE` - **precision-subtract**: `CHANGE -= FEE`
    4. If `CHANGE == 0` - remove the change output (freed resources go to a bit larger fee)
6. Sign and return tx.

Where **precision-subtract** means a complex process of checking if reducing the value of output might actually reduce the value of fee itself, so the output might be partially "refunded" back. Might be found in this function - https://github.com/input-output-hk/rust-cardano/blob/1e01a962e9e7c9c886c5f937747aa620729912d0/cardano/src/txbuild.rs#L125

An example of how "fees included" are already calculated in Rust, with additional example of **precision-subtract** might be found here: https://github.com/input-output-hk/rust-cardano/blob/1e01a962e9e7c9c886c5f937747aa620729912d0/cardano/src/wallet/rindex.rs#L109

Also note that there might be a case where output X is marked as `{fee: true}`, and we calculate the estimated fee, and it turnes out `X.v` is less than `FEE`. It seems like an error case right away, BUT it might be possible that `(X.v + cost(X)) >= FEE`, which means that removing output X will be enough to cover the fee, because each output adds some tiny cost to the overall transaction. So algorithm might be like this:

1. We find output X marked as `{fee: true}`
2. If `X.v >= FEE` - **precision-subtract** FEE from X, and if X.v turnes to be zero - remove X
3. If `X.v < FEE` - remove X, recalculate FEE and check if `(TOTAL_INPUT - TOTAL_OUTPUT) >= FEE` (note that total output now also includes the change output, if present). If freed difference covers new FEE - success. Else - throw error "Selected output is not enough to cover fees."

There also possible a case when this removed output is the only meaningful (non-change) one. For example - if I try to send 0.17 ADA to someone, and mark it as "fee included" - then the whole output might be removed to cover the fee, and transaction could turn out to have only change output which would make no sense to execute of course. In this case I think it would be ok to throw an error like "No meaningful outputs!".

But if I have specified two or more outputs, and the one marked for fee got cancelled out because of it - imo, it would be ok to create and return a tx like this, and then UI might confirm with the user that it's ok to send out.

Alternative could be to create outputs of zero value, which is ok from the protocol point of view, but would look quite weird, imo )

**Comment by vantuz-subhuman** [comment]
Also note that in the future we may want to also expand the API to allow to select **multiple** outputs to share fees (optionally in different proportions). So it would be really cool to implement this feature in a manner that would allow to add further changes without braking the API.

The best way to implement this for now, imo, would be to add a new field into the `TxOut` of type: `TxOutFeePolicy` (for example), and this new type would for now contain a simple "singleton" implementation `FullFee`. Validation procedure for now would be very simple:
1. If multiple outputs contains non-null `fee_policy` field - throw error
2. If there's no output with a non-null value - assume the change output is paying the fee

**Comment by SebastienGllmt** [comment]
I would also consider changing `{fee: true}` to `{fee: 1.0}` (or `{fee: 100}` if we want to avoid floats) that way in the future we can support ratios easily (two outputs, each with `{fee: 0.5}` for example)

**Comment by vantuz-subhuman** [comment]
> that way in the future we can support ratios easily

But I mean this comment above is just about exactly that 😁 (https://github.com/input-output-hk/rust-cardano/issues/353#issuecomment-448778853) 

If we do a new type with a single "flag" implementation now - later we can add a second implementation, like `FeePortion(int)`, which could validate inside constructor that specified value is between 1 and 100, etc.

And this would also add later other implementations with non-int parameters, if we come up with something else.
