### ISSUE TITLE
CircleCI: add minimal rust compiler version job too

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/rust-cardano#366]
We need to make sure we support a minimal compiler version in the circle ci jobs.

the minimal version should be `1.31.0` (edition: 2018).

**Comment by amias-iohk** [comment]
we are currently using - 
rustc 1.31.1 (b6c32da9b 2018-12-18)
cargo 1.31.0 (339d9f9c8 2018-11-16)

This appears to be configured by 
    docker:
      - image: rust:latest

Looks like this is built from this dockerfile 
https://github.com/rust-lang/docker-rust/blob/1d112bc218d6b7a5479a05fa652130d8e086564f/1.31.1/stretch/Dockerfile

**Comment by mzabaluev** [comment]
`rust:latest` will be updated to latest stable version whenever it is released.
To ensure that the build job uses rustc 1.31.1, use `rust:1.31.1`. This should be updated to subsequent 1.31.x patch releases if any more are made &mdash; we're interested in bug fixes while keeping the language feature support at the minimal 2018 edition version.
