### ISSUE TITLE
storage-units: add standalone executable tests

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/rust-cardano#372]
the crate contains a couple of features and APIs that we need to test independently: https://github.com/input-output-hk/rust-cardano/tree/master/storage-units/src

for example, there is the [`Lock`](https://github.com/input-output-hk/rust-cardano/blob/master/storage-units/src/utils/lock.rs) that needs testing. And there is the [`Append`](https://github.com/input-output-hk/rust-cardano/blob/master/storage-units/src/append.rs) that needs testings too.

the task is to:

* generate the documentation of this module: `cd storage-unit ; cargo doc --no-deps --open`
* analyses the APIs and propose a test plans for every module;
* write integration tests to verify it works as expected (there are some doc on what they are [here](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests) )

**Comment by amias-iohk** [comment]
it seems that i cannot get the lock module to create a lock , it seems the acquire function silently fails because it can only return OK. 
These issues have been seen before
https://github.com/input-output-hk/rust-cardano/issues/321

**Comment by mzabaluev** [comment]
> the lock constructor is only capable of returning Ok because acquire is run with ?

`?` means early return when the expression returns `Err`, returning the (possibly converted) error, so an acquire failure will produce an error.

> the acquire method can only return OK which mean you cannot know if it failed

This is a bug.

**Comment by amias-iohk** [comment]
maybe i have misunderstood the design of it but it seems useful to be able to query the lock and get a boolean for its lock state.

the lock code should NEVER overwrite an existing lock with a new pid
