### ISSUE TITLE
Bug in private key derivation for addresses - support old weird Daedalus scheme

### ISSUE THREAD

**Issue by vantuz-subhuman** [input-output-hk/rust-cardano#409]
## Abstract

Rust derivation scheme for V1 addresses assumes it should always use 2 level of **hardened** derivation - https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/wallet/rindex.rs#L219. The problem is that old versions of Daedalus (around 2017) were using both hardened and non-hardened indexes for the same address-derivation scheme (random indexes across the whole 32 bit range).

This means that there already exist a bunch of V1 addresses on the chain derived using a non-hardened second index. Rust code does not verify if derivation indexes are hardened, and just applies hardened scheme to them: https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/wallet/rindex.rs#L244

This means that if we have a V1 derived private key `P` and we have its matching derivation path from address attributes, and then we call Rust to produce a private key for this path - it produces private key `P' != P` which causes all sorts of problems where try to use V1 functionality in rust-cardano.

**Comment by vantuz-subhuman** [comment]
I am trying to understand where exactly the problem is happening, because the derived `key` is obviously wrong (because we get public key from it that doesn't match actual address) - https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/wallet/rindex.rs#L245-L248

So the problem must be in `.derive` function, which internally called `derive_private` here: https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/hdwallet.rs#L346-L348

This one: https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/hdwallet.rs#L924

And this function actually seem to be able to properly derive both hardened AND soft indexes, based on this piece of code: https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/hdwallet.rs#L939-L970

So the problem seem to potentially depend on the `scheme` parameter passed to the function, which determines `V1` (legacy) or `V2` (new) type of addresses/derivation, because soft derivation seem to be working fine for `V2`, but not for `V1`.

In the same piece of code we can see that fields dependent on the `scheme` parameter are:
1. `seri` - https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/hdwallet.rs#L941
2. `left` and `right` - https://github.com/input-output-hk/rust-cardano/blob/21e1febd8717977c8075765b0e4a51d7d9516d87/cardano/src/hdwallet.rs#L967-L970

All three fields are already hard to validate for me, cuz it's cryptography already 🙂 But from my understanding it was assumed that Soft derivation is never actually supposed to be called with `V1` scheme, and this might be the cause.

@vincenthz

**Comment by vantuz-subhuman** [comment]
> So the problem seem to potentially depend on the `scheme` parameter passed to the function, which determines `V1` (legacy) or `V2` (new) type of addresses/derivation, because soft derivation seem to be working fine for `V2`, but not for `V1`.

Ah, I guess the problem might be exactly in the fact that for `V1` there is NO soft derivation at all, and if scheme is `V1` - it supposed to use Hard derivation despite the index (because if index is valid - then it guaranteed to be from hardened range, and if it's old invalid index - then it still should be processed with hard derivaion).

**Comment by NicolasDP** [comment]
I believe this has been resolved in #411
