### ISSUE TITLE
Build error from Master branch

### ISSUE THREAD

**Issue by ItFlyingStart** [input-output-hk/rust-cardano#488]
I have pulled the lastest source codes from the master branch, but I couldn't build it because of the next errors:

> Compiling network-ntt v0.1.0 (C:\Git\Blockchain\IOHK\rust-cardano\network-ntt)
error[E0277]: the trait bound `P: tokio_connect::Connect` is not satisfied
  --> network-grpc\src\client.rs:84:31
   |
84 |         let mut make_client = Connect::new(peer, Default::default(), executor);
   |                               ^^^^^^^^^^^^ the trait `tokio_connect::Connect` is not implemented for `P`
   |
   = help: consider adding a `where P: tokio_connect::Connect` bound
   = note: required by `<tower_h2::client::Connect<C, E, S>>::new`

> error[E0599]: no method named `make_service` found for type `tower_h2::client::Connect<P, E, tower_grpc::BoxBody>` in the current scope
  --> network-grpc\src\client.rs:86:14
   |
86 |             .make_service(())
   |              ^^^^^^^^^^^^
   |
   = note: the method `make_service` exists but the following trait bounds were not satisfied:
           `tower_h2::client::Connect<P, E, tower_grpc::BoxBody> : tower_util::MakeService<_, _>`

> error: aborting due to 2 previous errors

> Some errors occurred: E0277, E0599.
> For more information about an error, try `rustc --explain E0277`.

![image](https://user-images.githubusercontent.com/5562995/53693592-e0619a80-3da2-11e9-93af-5cb0931ac95d.png)

**Comment by mzabaluev** [comment]
@ItFlyingStart Did you try `cargo update`?
Unfortunately, we cannot pin all tower-grpc dependencies to known-working revisions, so we have to deal with API drift.

**Comment by ItFlyingStart** [comment]
`cargo update` does the trick. Thanks.
