### ISSUE TITLE
HD version bytes for BIP-0032

### ISSUE THREAD

**Issue by eosfomogame** [input-output-hk/rust-cardano#666]
Hello guys, where can I find these BIP32 data (xpriv, xpub) for Cardano (yoroi wallet)
```
bitcoin: {
    messagePrefix: '\x18Bitcoin Signed Message:\n',
    bech32: 'bc',
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4
    },
    pubKeyHash: 0x00,
    scriptHash: 0x05,
    wif: 0x80
  }
```
https://github.com/satoshilabs/slips/blob/master/slip-0132.md
https://cardanolaunch.com/assets/Ed25519_BIP.pdf
https://bitcoin.stackexchange.com/questions/28380/i-want-to-generate-a-bip32-version-number-for-namecoin-and-other-altcoins
Thanks

**Comment by vincenthz** [comment]
there's no such thing currently with current cardano address/key. we use BIP32 + BIP44 on a different curve (ed25519) with specific registered cardano index, but we don't have a known prefix and we use base58.

The next format of address will be bech32 encoded, with a known prefix of 'ca' or 'ta', and there will be a bech32 version of public/private key also
