### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by eode** [input-output-hk/rust-cardano#748]
Title says it all.  There doesn't seem to be activity on this project.

**Comment by SebastienGllmt** [comment]
Probably you're looking for https://github.com/Emurgo/cardano-serialization-lib

This is the new project which is compatible with current Cardano mainnet

**Comment by mendesbarreto** [comment]
I am no sure, I'd like to use this sdk to play with Cardano in my Rust app....

**Comment by eode** [comment]
@mendesbarreto If you're talking about *this* library, then no.  If you're talking about the one he linked, https://github.com/Emurgo/cardano-serialization-lib, then yes.  It's got an MIT license.

**Comment by FrankC01** [comment]
Shouldn't the repo be archived? It's misleading otherwise if you aren't looking closely

**Comment by eode** [comment]
Yes, it should probably be archived.  Anyone have control of this repo?

**Comment by eode** [comment]
Yes, it probably should.

@SebastienGllmt @vincenthz @mzabaluev @NicolasDP  -  Do any of you have control of this repo to archive it?
