### ISSUE TITLE
spending protocol

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#85]
* gather information on how it's done
* add support for lowlevel protocol

**Comment by drozdziak1** [comment]
Hi @vincenthz, where do you "gather information on how it's done"? Is there publicly available protocol API docs anywhere?

**Comment by NicolasDP** [comment]
hi @drozdziak1 ,

Unfortunately, the only documentation of the low level native protocol is the code reference in [`cardano-sl`](https://github.com/input-output-hk/cardano-sl);

You may find the work as been bootstrapped here [`7813ca4c722892a6dd5f34e89f111b1ece05bad9`](https://github.com/input-output-hk/rust-cardano/commit/7813ca4c722892a6dd5f34e89f111b1ece05bad9) the code has not been tested yet.

**Comment by NicolasDP** [comment]
done in #210
