### ISSUE TITLE
more block validation

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#89]
Add some further blocks validation (header, body, proofs, etc)

We can see this as multi level validation (each back by their own function):

1. At the block level: check that the block is consistent with itself:
   * all hashes matches: e.g. body hash matches the one in the header, but other hashes also.
   * transactions semantic are correct: at least 1 input, at least 1 output, input sum matches output sum and fees, check fees according to a fee calculator
   * etc
2. At the epoch level: check that all the block within an epoch are valid:
   * signature verified
   * slot leaders keys (available in genesis block), matches each block signature.
3. Overall: check that utxo spent are valid.

**Comment by edolstra** [comment]
I guess this can be closed? The only thing (AFAIK) that we're not validating is the slot leader selection, but that will soon be obsolete anyway.

**Comment by vincenthz** [comment]
yep @edolstra
