### ISSUE TITLE
block genesis finish parsing / printing

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/rust-cardano#90]
Finish parsing of genesis blocks (body), and oretty printing of block

**Comment by plredmond** [comment]
are you open to using a library for the pretty printing, such as https://docs.rs/pretty/0.4.0/pretty/ ?

**Comment by plredmond** [comment]
Ok, so there's a generic prettyprinter now. Next steps:

- [ ] parse genesis blocks
- [ ] implement `Pretty` for genesis blocks
